# Generated by Django 3.2.11 on 2022-02-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Employee_name2',
        ),
    ]
