# Generated by Django 3.2.11 on 2022-02-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0003_employees_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_new',
            name='emp_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
